### ISSUE TITLE
How can i add mobile controll

### ISSUE THREAD

**Issue by oktaykurt** [saiichihashimoto/dinosaurgame#19]
I want to run this game on mobile platforms. How can i add a basic touch controll. I need only 1 touch function for jump and start game. I don't want to use duck function.

**Comment by saiichihashimoto** [comment]
Sorry, didn't mean to add/remove that label. Go into the `Scenes` folder and open `Game.unity`. Let me know if that doesn't work for you.

**Comment by saiichihashimoto** [comment]
Unity has documentation on it's [touch features](https://docs.unity3d.com/ScriptReference/Touch.html) that you should look at and, if you need support, reach out to them.
