### ISSUE TITLE
I don't see anything when I Open the project

### ISSUE THREAD

**Issue by fguillen** [saiichihashimoto/dinosaurgame#20]
I tried to open the Project but the Scene is empty and there is nothing in the Hierarchy: 

- https://imagebin.ca/v/3XfW3KHg0DkC

How can I set up the project?

Thanks

**Comment by saiichihashimoto** [comment]
Sorry, didn't mean to add/remove that label. Go into the `Scenes` folder and open `Game.unity`. Let me know if that doesn't work for you.
